[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
rusqlite = { version = "0.33.0", optional = true }

[features]
server = ["dioxus/server", "dep:rusqlite"]
